### ISSUE TITLE
Support for hooks

### ISSUE THREAD

**Issue by alp82** [ruanyl/reapex#3]
Are you planning to support react/redux hooks? It might be worth the effort since they are gaining popularity rapidly.

**Comment by ruanyl** [comment]
Hi @alp82 
I haven't thought this thoroughly. But I think one way of using hooks is just using `react-redux` hooks which were added since `react-redux@v7.1.0`

**Comment by ruanyl** [comment]
Updated example in REAMDE to use hooks
