### ISSUE TITLE
Support immer

### ISSUE THREAD

**Issue by 87Hz** [ruanyl/reapex#6]
It would be nice to support immer in mutations.

**Comment by ruanyl** [comment]
Hey @87Hz , thank you for the suggestion. Starting from `v1.0.0-beta.2`, you can use reapex plugin [reapex-plugin-immer](https://www.npmjs.com/package/reapex-plugin-immer) to enable immer support.

Example:
```typescript
import { App } from 'reapex'
import immer from 'reapex-plugin-immer'

const app = new App()
app.use(immer)

const model = app.model('counter', { total: 0 })
const [mutations] = model.mutations({
  // state here will be an immer draft object
  increase: () => state => {
    state.total = state.total + 1
    return state
  },
})
```

**Comment by 87Hz** [comment]
Awesome, thanks @ruanyl, I am closing this issue now.
